Add missing "#include <stddef.h>" to fix the build on macOS
... after 19d7684ca10f.

Prevents:
gateway.c:845:18: error: call to undeclared function 'offsetof'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

Fixes SF#150.